"""Learning-material page renderer (usability rounds 3-4).

One pre-styled, self-contained template shared by every generated material so
documents, images, video embeds, self-checks, interactive widgets, and small
learning games all look consistent (OpenAI-flavored, light/dark aware).
No external requests.

Usage (from skills or the agent):
    from harness.material_page import build_material_page
    build_material_page(root, title="...", kc="concurrency",
                        body_html="<p>...</p>", image="diagram.png",
                        video="clip.mp4", questions=["...?"],
                        interactive_html="<div id='game'>...</div><script>...</script>")
`interactive_html` is an escape hatch for dynamic/gamified content: any
self-contained HTML+JS block (no external requests) is mounted inside a styled
card, so generated games and simulations inherit the page design.
Writes learning/materials/<slug>.html and returns the path.
"""
from __future__ import annotations

import html
import re
import time
from pathlib import Path

_TEMPLATE = """<html><head><meta charset='utf-8'>
<meta name='viewport' content='width=device-width,initial-scale=1'>
<title>{title}</title><style>
:root {{ --bg:#f7f7f8; --card:#fff; --ink:#0d0d0d; --sub:#6e6e80; --line:#ececf1;
        --accent:#10a37f; --chip:#f0f0f3 }}
@media (prefers-color-scheme:dark) {{ :root {{ --bg:#161618; --card:#212123;
        --ink:#ececf1; --sub:#9b9ba7; --line:#39393f; --chip:#2c2c30 }} }}
* {{ box-sizing:border-box }}
body {{ font-family:-apple-system,'Segoe UI',Inter,sans-serif; margin:0;
       background:var(--bg); color:var(--ink); -webkit-font-smoothing:antialiased }}
header {{ max-width:46rem; margin:0 auto; padding:2.2rem 1.4rem 0 }}
header h1 {{ margin:0; font-size:1.45rem; letter-spacing:-.02em }}
header small {{ color:var(--sub) }}
main {{ max-width:46rem; margin:1.2rem auto 3rem; padding:0 1.4rem }}
.card {{ background:var(--card); border:1px solid var(--line); border-radius:14px;
        padding:1.3rem 1.5rem; box-shadow:0 1px 2px rgba(0,0,0,.04); margin-bottom:1rem }}
img,video {{ max-width:100%; border-radius:10px; margin:.4rem 0 }}
.selfcheck {{ border-left:3px solid var(--accent) }}
.selfcheck h2 {{ margin:0 0 .5rem; font-size:1rem }}
.selfcheck ol {{ margin:.2rem 0 .6rem 1.2rem; padding:0 }}
.interactive h2 {{ margin:0 0 .5rem; font-size:1rem }}
footer {{ text-align:center; color:var(--sub); font-size:.8rem; margin:1.4rem 0 }}
code {{ background:var(--chip); padding:.12rem .35rem; border-radius:5px; font-size:.9em }}
button {{ font:inherit; background:var(--accent); color:#fff; border:none;
         border-radius:8px; padding:.45rem .9rem; cursor:pointer }}
button:hover {{ filter:brightness(1.08) }}
small {{ color:var(--sub) }}
</style></head><body>
<header><h1>{title}</h1><small>concept: {kc} &middot; generated by oh-my-brain &middot; stays on this machine</small></header>
<main>
{media}
<div class='card'>{body}</div>
{interactive}
{selfcheck}
</main>
<footer>oh-my-brain learning material</footer>
</body></html>"""


def _slug(title: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    return s or f"material-{int(time.time())}"


def build_material_page(root: Path | str, *, title: str, kc: str, body_html: str,
                        image: str | None = None, video: str | None = None,
                        questions: list[str] | None = None,
                        interactive_html: str | None = None,
                        quiz_items: list[dict] | None = None) -> Path:
    """quiz_items: [{"q": str, "choices": [str,...], "answer_idx": int}] renders a
    clickable quiz whose outcomes POST to the local study server (/record) and
    land in the learner record like agent-graded answers."""
    root = Path(root)
    out_dir = root / "learning" / "materials"
    out_dir.mkdir(parents=True, exist_ok=True)

    media = ""
    if image:
        media += (f"<div class='card'><img src='{html.escape(image)}' "
                  f"alt='{html.escape(title)}'></div>")
    if video:
        media += (f"<div class='card'><video controls src='{html.escape(video)}'>"
                  f"video: {html.escape(video)}</video></div>")

    interactive = ""
    if interactive_html:
        interactive = (f"<div class='card interactive'><h2>Try it</h2>"
                       f"{interactive_html}</div>")

    quiz = ""
    if quiz_items:
        import json as _json
        quiz = ("<div class='card selfcheck'><h2>Quiz (recorded)</h2><div id='omb-quiz'></div>"
                "<div id='omb-quiz-msg'><small>Pick an answer; your result is saved to "
                "your learner record when the study server is running "
                "(python3 -m harness.study_server).</small></div>"
                f"<script>const OMBQ={_json.dumps(quiz_items)};const KCN={_json.dumps(kc)};" + """
const qroot=document.getElementById('omb-quiz'),qmsg=document.getElementById('omb-quiz-msg');
OMBQ.forEach((it,qi)=>{const d=document.createElement('div');
 d.innerHTML='<p><b>Q'+(qi+1)+'.</b> '+it.q+'</p>';
 it.choices.forEach((c,ci)=>{const b=document.createElement('button');
  b.textContent=c; b.style.margin='3px';
  b.onclick=async()=>{const ok=ci===it.answer_idx?1:0;
   d.querySelectorAll('button').forEach(x=>x.disabled=true);
   b.style.outline=ok?'3px solid #10a37f':'3px solid #ef4146';
   try{await fetch('/record',{method:'POST',headers:{'Content-Type':'application/json'},
     body:JSON.stringify({kc_hint:KCN,question:it.q,correct:ok})});
     qmsg.innerHTML='<small>Saved to your learner record ('+(ok?'correct':'incorrect')+'). '+
       (ok?'Nice.':'The agent will follow up with material on this.')+'</small>';}
   catch(e){qmsg.innerHTML='<small>Answered '+(ok?'correctly':'incorrectly')+
     ' - not saved (start: python3 -m harness.study_server).</small>';}};
  d.appendChild(b);});
 qroot.appendChild(d);});
</script>""" + "</div>")

    selfcheck = ""
    if questions:
        items = "".join(f"<li>{html.escape(q)}</li>" for q in questions)
        selfcheck = (f"<div class='card selfcheck'><h2>Check yourself</h2>"
                     f"<ol>{items}</ol>"
                     f"<small>Answers are not shown here on purpose; reply to the "
                     f"agent and it will grade you.</small></div>")

    out = out_dir / f"{_slug(title)}.html"
    out.write_text(_TEMPLATE.format(
        title=html.escape(title), kc=html.escape(kc),
        media=media, body=body_html, interactive=interactive,
        selfcheck=quiz + selfcheck), encoding="utf-8")
    return out
